project_id = "fpmlrhpmtmaurrnhsmca"

[functions.generate-poster-caption]
verify_jwt = false

[functions.generate-ai-poster]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.search-unsplash]
verify_jwt = false

[functions.analyze-image-structure]
verify_jwt = false

[functions.remove-background]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.preview-voice]
verify_jwt = false

[functions.import-figma-design]
verify_jwt = false
